name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 8.0.232+9.1
        distribution: 'adopt'
        cache: gradle

   #  - name: Grant execute permission for gradlew
      # run: chmod +x gradlew
      
    # - name: Build with Gradle
      # run: ./gradlew build
      
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: Github Actions job result
        to: 2556536414@qq.com
        from: TeaOf 
        secure: true
        body: Build job of ${{github.repository}} completed successfully!
